"""Shared literals for inference-engine unit tests."""

TRANSACTION_ID = "txn-1"

VALID_AMOUNT = 99.99
INVALID_ZERO_AMOUNT = 0.0
INVALID_NEGATIVE_AMOUNT = -1.0

VALID_MERCHANT_RISK_SCORE = 0.5
INVALID_MERCHANT_RISK_ABOVE_ONE = 1.5

VALID_HOUR_OF_DAY = 14
INVALID_HOUR_OF_DAY = 24

VALID_DAY_OF_WEEK = 3
INVALID_DAY_OF_WEEK = 0

FRAUD_PROBABILITY = 0.42
INVALID_FRAUD_PROBABILITY_ABOVE_ONE = 1.1

MODEL_VERSION = "v1"

FEATURE_NAME = "amount"
FEATURE_VALUE = 200.0
FEATURE_CONTRIBUTION = 0.15
FEATURE_DIRECTION = "increases"

ERROR_MESSAGE = "something failed"
VALIDATION_MESSAGE = "invalid input"

LOG_CONTEXT = "scoring transaction"
LOG_EXCEPTION_MESSAGE = "boom"

HTTP_STATUS_OK = 200
HTTP_STATUS_BAD_REQUEST = 400
HTTP_STATUS_INTERNAL_SERVER_ERROR = 500
HTTP_STATUS_SERVICE_UNAVAILABLE = 503
