alter table transaction_feature_vectors
    add column log_amount double precision not null default 0,
    add column log_seconds_since_last_transaction double precision not null default 0,
    add column log_velocity1_hour double precision not null default 0,
    add column amount_times_merchant_risk double precision not null default 0,
    add column amount_times_ip_risk double precision not null default 0,
    add column risk_score_product double precision not null default 0,
    add column ip_device_risk double precision not null default 0,
    add column country_ip_risk double precision not null default 0,
    add column velocity_amount_interaction double precision not null default 0,
    add column recency_velocity double precision not null default 0,
    add column card_age_amount_ratio double precision not null default 0,
    add column amount_deviation double precision not null default 0,
    add column is_night boolean not null default false,
    add column night_amount_ratio double precision not null default 0,
    add column velocity_intensity double precision not null default 0;
