server:
  port: 8084

spring:
  application:
    name: risk-action-handler

app:
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      transactions-scored-topic: ${KAFKA_TRANSACTIONS_SCORED_TOPIC:transactions.scored}
      consumer-group-id: ${KAFKA_CONSUMER_GROUP_ID:risk-action-handler}
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:earliest}
